name: Python actions
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check repository
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Setup pipenv
        run: python -m pip install --upgrade pipenv wheel

      - name: Install pipenv requirements
        run: |
          pipenv install

      - name: Run linter
        run: pipenv run pycodestyle .

      - name: Run test
        run: pipenv run py.test
